name: 'Getnighthawk Layer5'
description: 'Publish getnighthawk assets'

inputs:
  repo:
    description: 'org/repo to publish actions to'
    required: false
    default: ''
  version:
    description: 'version of the release'
    required: false
    default: 'latest'
  token:
    description: 'optional Personal Access Token to access external repository'
    required: false
    default: ''
  os:
    description: 'Build Operating System. Eg: ubuntu-18.04, macos-latest....'
    required: false
  architecture:
    description: 'Build Architecture. Eg: amd64,arm...'
    required: false

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/scripts/setup.sh
      env:
        INPUT_OS: ${{ inputs.os }}
        INPUT_ARCHITECTURE: ${{ inputs.architecture }}
      shell: bash
    - run: ${{ github.action_path }}/scripts/build.sh
      shell: bash
    - run: ${{ github.action_path }}/scripts/verify.sh
      shell: bash
    - run: ${{ github.action_path }}/scripts/publish.sh
      env:
        INPUT_REPO: ${{ inputs.repo }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_OS: ${{ inputs.os }}
        INPUT_ARCHITECTURE: ${{ inputs.architecture }}
      shell: bash

outputs:
  version:
    description: 'The version of the release or tag'

branding:
  icon: 'download-cloud'
  color: 'blue'